name: Build iOS App

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build unsigned IPA
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app
        
      - name: Build Payload
        run: |
          cd app
          xcodebuild -project Madeira.xcodeproj -scheme Madeira -configuration Release -destination 'generic/platform=iOS' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CONFIGURATION_BUILD_DIR=${GITHUB_WORKSPACE}/build
      
      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r build/Madeira.app Payload/
          zip -r Madeira.ipa Payload
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Madeira-iOS16
          path: Madeira.ipa
